language: rust
rust:
  - 1.36.0
  - nightly
  - beta
  - stable
script:
  - cargo test
  - cargo test --features serde
  - "[ $TRAVIS_RUST_VERSION != nightly ] || cargo test --all-features"
  - "[ $TRAVIS_RUST_VERSION != nightly ] || cargo bench"
