[package]
name = "smallvec"
version = "0.4.5"
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
license = "MPL-2.0"
repository = "https://github.com/servo/rust-smallvec"
description = "'Small vector' optimization: store up to a small number of items on the stack"
keywords = ["small", "vec", "vector", "stack", "no_std"]
readme = "README.md"
documentation = "http://doc.servo.org/smallvec/"

[features]
heapsizeof = ["heapsize", "std"]
std = []
default = ["std"]

[lib]
name = "smallvec"
path = "lib.rs"

[dependencies]
heapsize = { version = "0.4", optional = true }
serde = { version = "1", optional = true }

[dev_dependencies]
bincode = "0.8"
